sudo: false
language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - android-25
    - build-tools-25
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

jdk: oraclejdk8

notifications:
  email: false

before_install:
  - ./gradlew --version

script:
  - ./gradlew check